### ISSUE TITLE
Include versions for each dependency

### ISSUE THREAD

**Issue by bmish** [pmmmwh/staledeps#167]
There could be additional columns in the output for each dependency, like:

* Last publish, version
* Last publish, date (existing column)
* Most recent version in requested range, version
* Most recent version in requested range, date

Note that I specified "Most recent version in requested range" because package.json may specify `^1.0` as the requested range but yarn.lock could have any number of versions in that range (`1.7`, etc), or even versions outside that range due to transitive dependencies. So it's not trivial to say what single version a dependency is on. Although you can see what versions of a dependency are present using `yarn why eslint` for example.

**Comment by pmmmwh** [comment]
I agree that we should add a version field to see the latest published version - but for things like latest "requested" version I would refrain from doing simply because we would have to do a lot of dependency resolution work - which is also potentially inaccurate because we don't know how the whole tree looks (transitive dependencies, peer dependencies, etc.).
